// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkBookingAvailability = `-- name: CheckBookingAvailability :one

Select count(*) from booking where id_rooms = $1 and status in ('Pending','done')
and(start_time < $2 and end_time > $3 )
`

type CheckBookingAvailabilityParams struct {
	IDRooms   uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CheckBookingAvailability(ctx context.Context, arg CheckBookingAvailabilityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkBookingAvailability, arg.IDRooms, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one

insert into booking(
    id,id_user,id_rooms,start_time,end_time,total_price,status
)values(
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, id_user, id_rooms, start_time, end_time, total_price, status, created_at, updated_at
`

type CreateBookingParams struct {
	ID         uuid.UUID
	IDUser     uuid.UUID
	IDRooms    uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
	TotalPrice string
	Status     Stats
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ID,
		arg.IDUser,
		arg.IDRooms,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDRooms,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec

Delete from booking where id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBooking = `-- name: GetBooking :many

select b.start_time,b.end_time,b.total_price,b.status,r.nama as nama_ruangan ,u.nama as nama_user from booking b inner join rooms r on b.id_rooms = r.id 
inner join users u on b.id_user = u.id OFFSET $1 LIMIT $2
`

type GetBookingParams struct {
	Offset int32
	Limit  int32
}

type GetBookingRow struct {
	StartTime   time.Time
	EndTime     time.Time
	TotalPrice  string
	Status      Stats
	NamaRuangan string
	NamaUser    string
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) ([]GetBookingRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooking, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingRow
	for rows.Next() {
		var i GetBookingRow
		if err := rows.Scan(
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.Status,
			&i.NamaRuangan,
			&i.NamaUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one

update booking set start_time = $1,end_time = $2,status = $3, total_price = $4 where id = $5
RETURNING id, id_user, id_rooms, start_time, end_time, total_price, status, created_at, updated_at
`

type UpdateBookingParams struct {
	StartTime  time.Time
	EndTime    time.Time
	Status     Stats
	TotalPrice string
	ID         uuid.UUID
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.TotalPrice,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDRooms,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
