// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fasilitas.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFasilitas = `-- name: CreateFasilitas :one

insert into fasilitas(
    id,
    nama
) values(
    $1,$2
)
RETURNING id, nama
`

type CreateFasilitasParams struct {
	ID   uuid.UUID
	Nama string
}

func (q *Queries) CreateFasilitas(ctx context.Context, arg CreateFasilitasParams) (Fasilita, error) {
	row := q.db.QueryRowContext(ctx, createFasilitas, arg.ID, arg.Nama)
	var i Fasilita
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}

const deleteFasilitas = `-- name: DeleteFasilitas :exec

Delete from fasilitas where id = $1
`

func (q *Queries) DeleteFasilitas(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFasilitas, id)
	return err
}

const getFasilitas = `-- name: GetFasilitas :one

select nama from fasilitas where id = $1
`

func (q *Queries) GetFasilitas(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFasilitas, id)
	var nama string
	err := row.Scan(&nama)
	return nama, err
}

const updatefasilitas = `-- name: Updatefasilitas :one

update fasilitas set nama = $1 where id = $2
RETURNING id, nama
`

type UpdatefasilitasParams struct {
	Nama string
	ID   uuid.UUID
}

func (q *Queries) Updatefasilitas(ctx context.Context, arg UpdatefasilitasParams) (Fasilita, error) {
	row := q.db.QueryRowContext(ctx, updatefasilitas, arg.Nama, arg.ID)
	var i Fasilita
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}
