// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Roles string

const (
	RolesAdmin Roles = "Admin"
	RolesUser  Roles = "user"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type Stats string

const (
	StatsPending   Stats = "pending"
	StatsApproved  Stats = "approved"
	StatsDone      Stats = "done"
	StatsCancelled Stats = "cancelled"
)

func (e *Stats) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Stats(s)
	case string:
		*e = Stats(s)
	default:
		return fmt.Errorf("unsupported scan type for Stats: %T", src)
	}
	return nil
}

type NullStats struct {
	Stats Stats
	Valid bool // Valid is true if Stats is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStats) Scan(value interface{}) error {
	if value == nil {
		ns.Stats, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Stats.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStats) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Stats), nil
}

type Booking struct {
	ID         uuid.UUID
	IDUser     uuid.UUID
	IDRooms    uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
	TotalPrice string
	Status     Stats
}

type Fasilita struct {
	ID   uuid.UUID
	Nama string
}

type Room struct {
	ID           uuid.UUID
	Nama         string
	Kapasitas    int32
	PricePerHour string
	Description  string
}

type User struct {
	ID           uuid.UUID
	Nama         string
	Email        string
	HashPassword string
	Role         Roles
	CreatedAt    time.Time
}
