// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createroom = `-- name: Createroom :one

insert into rooms(
    id,nama,kapasitas,price_per_hour,description,created_at,updated_at
) values(
    $1,$2,$3,$4,$5,$6,$7
)

RETURNING id, nama, kapasitas, price_per_hour, description, created_at, updated_at
`

type CreateroomParams struct {
	ID           uuid.UUID
	Nama         string
	Kapasitas    int32
	PricePerHour string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) Createroom(ctx context.Context, arg CreateroomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createroom,
		arg.ID,
		arg.Nama,
		arg.Kapasitas,
		arg.PricePerHour,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Kapasitas,
		&i.PricePerHour,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec

Delete from rooms where id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :many

select r.nama,r.kapasitas,r.price_per_hour,b.status as booking_status from rooms r inner join booking b on b.id_rooms = r.id OFFSET $1 LIMIT $2
`

type GetRoomParams struct {
	Offset int32
	Limit  int32
}

type GetRoomRow struct {
	Nama          string
	Kapasitas     int32
	PricePerHour  string
	BookingStatus Stats
}

func (q *Queries) GetRoom(ctx context.Context, arg GetRoomParams) ([]GetRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoom, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomRow
	for rows.Next() {
		var i GetRoomRow
		if err := rows.Scan(
			&i.Nama,
			&i.Kapasitas,
			&i.PricePerHour,
			&i.BookingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomDetail = `-- name: GetRoomDetail :one

select r.nama,r.kapasitas,r.price_per_hour,r.kapasitas,b.status as booking_status from rooms r inner join booking b on b.id_rooms = r.id where r.id = $1 OFFSET $2 LIMIT $3
`

type GetRoomDetailParams struct {
	ID     uuid.UUID
	Offset int32
	Limit  int32
}

type GetRoomDetailRow struct {
	Nama          string
	Kapasitas     int32
	PricePerHour  string
	Kapasitas_2   int32
	BookingStatus Stats
}

func (q *Queries) GetRoomDetail(ctx context.Context, arg GetRoomDetailParams) (GetRoomDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomDetail, arg.ID, arg.Offset, arg.Limit)
	var i GetRoomDetailRow
	err := row.Scan(
		&i.Nama,
		&i.Kapasitas,
		&i.PricePerHour,
		&i.Kapasitas_2,
		&i.BookingStatus,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one

update rooms set nama = $1, kapasitas = $2, price_per_hour = $3, description = $4 where id = $5
RETURNING id, nama, kapasitas, price_per_hour, description, created_at, updated_at
`

type UpdateRoomParams struct {
	Nama         string
	Kapasitas    int32
	PricePerHour string
	Description  string
	ID           uuid.UUID
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.Nama,
		arg.Kapasitas,
		arg.PricePerHour,
		arg.Description,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Kapasitas,
		&i.PricePerHour,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
