// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_fasilitas.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFasilitas_Ruangan = `-- name: CreateFasilitas_Ruangan :one

insert into fasilitas_ruangan(
    id,id_room,id_fasilitas 
) values (
    $1,$2,$3
)
RETURNING id, id_room, id_fasilitas
`

type CreateFasilitas_RuanganParams struct {
	ID          uuid.UUID
	IDRoom      uuid.UUID
	IDFasilitas uuid.UUID
}

func (q *Queries) CreateFasilitas_Ruangan(ctx context.Context, arg CreateFasilitas_RuanganParams) (FasilitasRuangan, error) {
	row := q.db.QueryRowContext(ctx, createFasilitas_Ruangan, arg.ID, arg.IDRoom, arg.IDFasilitas)
	var i FasilitasRuangan
	err := row.Scan(&i.ID, &i.IDRoom, &i.IDFasilitas)
	return i, err
}
