// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUsers = `-- name: CreateUsers :one

insert into users(
    id,nama,email,hash_password,role,created_at
) values(
    $1,$2,$3,$4,$5,$6
)

RETURNING id, nama, email, hash_password, role, created_at
`

type CreateUsersParams struct {
	ID           uuid.UUID
	Nama         string
	Email        string
	HashPassword string
	Role         Roles
	CreatedAt    time.Time
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers,
		arg.ID,
		arg.Nama,
		arg.Email,
		arg.HashPassword,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Email,
		&i.HashPassword,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec

Delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUsers = `-- name: GetUsers :one

select nama,email,hash_password,role from users where id = $1
`

type GetUsersRow struct {
	Nama         string
	Email        string
	HashPassword string
	Role         Roles
}

func (q *Queries) GetUsers(ctx context.Context, id uuid.UUID) (GetUsersRow, error) {
	row := q.db.QueryRowContext(ctx, getUsers, id)
	var i GetUsersRow
	err := row.Scan(
		&i.Nama,
		&i.Email,
		&i.HashPassword,
		&i.Role,
	)
	return i, err
}

const getUserslist = `-- name: GetUserslist :many

select nama,email,hash_password from users where id = $1 order by created_at desc LIMIT $2 OFFSET $3
`

type GetUserslistParams struct {
	ID     uuid.UUID
	Limit  int32
	Offset int32
}

type GetUserslistRow struct {
	Nama         string
	Email        string
	HashPassword string
}

func (q *Queries) GetUserslist(ctx context.Context, arg GetUserslistParams) ([]GetUserslistRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserslist, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserslistRow
	for rows.Next() {
		var i GetUserslistRow
		if err := rows.Scan(&i.Nama, &i.Email, &i.HashPassword); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one

update users set nama = $1, email = $2 , hash_password = $3 where id = $4
RETURNING id, nama, email, hash_password, role, created_at
`

type UpdateUserParams struct {
	Nama         string
	Email        string
	HashPassword string
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Nama,
		arg.Email,
		arg.HashPassword,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Email,
		&i.HashPassword,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
